### PR TITLE
[tests] add test suite

### PR DESCRIPTION
**Pull request by thomasleveil**
This will help validate that new changes and new pull requests don't break the build of the docker image and that the built image is capable of running `/usr/share/jenkins/slave.jar` through ssh.

The test framework in use is [bats](https://github.com/sstephenson/bats/blob/master/README.md).

requirements are:

- bats
- docker
- curl
- ssh

### CODE REVIEW

**Comment by ndeloof** [comment]
I have setup jenkins.ci.cloudbees.com with a dedicated docker slave which could run such CI builds
https://jenkins.ci.cloudbees.com/job/docker/job/ssh-slave/1/console
I'd prefer not to rely on travis-ci :-\
Can you please rewrite this pull-request accordingly ?

**Comment by thomasleveil** [comment]
I will see what I can do ;)
I'll be at the _Continuous Delivery avec Jenkins et Docker_ event in Rennes thursday, maybe we can have a chat there

**Comment by ndeloof** [comment]
hoho, le monde est petit :)

**Comment by thomasleveil** [comment]
what about now? :honeybee: or :bug:

**Comment by ndeloof** [comment]
thanks !

**Pull request merged**
