### PR TITLE
fix permission of /usr/share/jenkins

### PR DESCRIPTION
**Pull request by ydubreuil**
and download openssh server at the beginning

### CODE REVIEW

**Comment by ndeloof** [comment]
command order in Dockerfile is designed to share layers with https://github.com/jenkinsci/docker-jnlp-slave/blob/master/Dockerfile
IIUC moving sshd isn't required for this fix.

**Comment by ndeloof** [comment]
I guess same change should apply to https://github.com/jenkinsci/docker-jnlp-slave/blob/master/Dockerfile#L29, right ?

**Comment by ydubreuil** [comment]
Yes, it should

**Comment by ndeloof** [comment]
fixed by https://github.com/jenkinsci/docker-ssh-slave/commit/a998e7415f482e11d387b57e986894b1f6da1948

**Pull request closed without merging**
